import React from "react";
import "../About/about.css";
import Nav from "../Home/Nav";
import Hero from "./Hero";
import Footer from "../Footer/Footer";

function About() {
  return (
    <div>
      <Nav />
      <Hero
        heading="About Starter"
        p={
          <>
            Starter is a “starter” theme designed for simplicity and minimalism.
            It is particularly suitable for personal blogs. It is designed by <a href="#">nrk9819</a>. The figma design file available to <a className="download" href="#">download for free</a>🤩 under <a href="#">CC BY 4.4</a>
          </>
        }
        p2={
          <>
            I plan to implement this theme in a variety of site generators and
            content management systems. My first priorities are enhance, 11ty,
            astro and ghost (CMS). In the future, there will also be Hugo,
            Solidstart, Hono, Deno Fresh, Vitepress and SvelteKit versions.
            Codes for every implementation will be available on my github.
          </>
        }
        p3={
          <>
            Contents in this site, other than this page and external links are
            dummy and generated by AI. They don’t serve any purpose but being
            placeholders. All images are downloaded from Unsplash.
          </>
        }
      />
      <Footer />
    </div>
  );
}

export default About;
