import React from "react";
import cover from "../../assets/cover-image.png";

function Hero(props) {
  return (
    <div className="hero">
      <h2>{props?.heading}</h2>
      <img src={cover} alt={props?.alt} />
      <p>
        Starter is a “starter” theme designed for simplicity and minimalism. It
        is particularly suitable for personal blogs. It is designed by <a href="#">nrk9819</a>.
        The figma design file available to <a className="download"  href="#">download for free</a> 🤩 under <a href="#">CC BY 4.4</a>
      </p>
      <p>
        I plan to implement this theme in a variety of site generators and
        content management systems. My first priorities are enhance, 11ty, astro
        and ghost (CMS). In the future, there will also be Hugo, Solidstart,
        Hono, Deno Fresh, Vitepress and SvelteKit versions. Codes for every
        implementation will be available on my github.
      </p>
      <p>
        Contents in this site, other than this page and external links are dummy
        and generated by AI. They don’t serve any purpose but being
        placeholders. All images are downloaded from Unsplash.
      </p>
    </div>
  );
}

export default Hero;
